### ISSUE TITLE
0template Can't guess MIME type of tar.zst files

### ISSUE THREAD

**Issue by pmiess** [0install/0template#18]
from the apps repo libs folder
```
$ 0watch gmp.watch.py
downloading new db file
mingw-w64-x86_64-gmp-6.2.1-1-any.pkg.tar.zst has valid md5
mingw-w64-x86_64-gmp-6.2.1-1-any.pkg.tar.zst has valid sha256
mingw-w64-x86_64-gmp-6.2.1-1-any.pkg.tar.zst has valid pgp signature
downloading new db file
mingw-w64-i686-gmp-6.2.1-1-any.pkg.tar.zst has valid md5
mingw-w64-i686-gmp-6.2.1-1-any.pkg.tar.zst has valid sha256
mingw-w64-i686-gmp-6.2.1-1-any.pkg.tar.zst has valid pgp signature
Traceback (most recent call last):
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_GHJMUQA4THAAAG62R4R55U2CLFGHNVIRH2TTBLKYH4SKBMZF7JPQ/0template.py", line 81, in <module>
    retrieval.process_elements(impl, impl, template_dir)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_GHJMUQA4THAAAG62R4R55U2CLFGHNVIRH2TTBLKYH4SKBMZF7JPQ/retrieval.py", line 22, in process_elements
    process_archive(elem, impl, template_dir)
  File "/home/pmiess/.cache/0install.net/implementations/sha256new_GHJMUQA4THAAAG62R4R55U2CLFGHNVIRH2TTBLKYH4SKBMZF7JPQ/retrieval.py", line 35, in process_archive
    assert mime_type, "Can't guess MIME type from {href}".format(href = href)
AssertionError: Can't guess MIME type from http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gmp-6.2.1-1-any.pkg.tar.zst
```

note that the db is signed with a new key available here https://github.com/msys2/MSYS2-keyring/blob/master/msys2.gpg that needs to be imported to validate.
```
--- a/mingw64watch.py
+++ b/mingw64watch.py
@@ -29,6 +29,10 @@ def get_valid_db(db_url, dst_file):
         pkg_key = key_file.read()
         gpg.import_keys(pkg_key)

+    with open(path.join(path.dirname(__file__), 'msys2.gpg')) as key_file:
+        pkg_key = key_file.read()
+        gpg.import_keys(pkg_key)
+
     result = gpg.verify_file(sig, data_filename=dst_file, close_file=False)
     if result.trust_level is None or result.trust_level <= result.TRUST_NEVER:
         print('downloading new db file')
```

**Comment by bastianeicher** [comment]
@talex5 Do you think adding support for `.tar.zst` to the Python and/or OCaml versions of Zero Install is feasible?

**Comment by talex5** [comment]
Adding a new compression format would probably just means adding another line here:

https://github.com/0install/0install/blob/5555f2e456c59a1e640cc096781a832956045d28/src/zeroinstall/archive.ml#L283

and then adding the right flag to tar:

https://github.com/0install/0install/blob/5555f2e456c59a1e640cc096781a832956045d28/src/zeroinstall/archive.ml#L151

**Comment by bastianeicher** [comment]
@talex5 I gave this a try in 0install/0install#175.

We'd also need to update the Python version of 0install though, in order for tools like 0template to be able to work with `.tar.zst` archives.
