### ISSUE TITLE
<file> in <recipe> leads to problem with MIME type guessing

### ISSUE THREAD

**Issue by bastianeicher** [0install/0template#2]
A template with
```xml
<recipe>
  <archive href="http://some/archive.zip" type="application/zip"/>
  <file href="http://some/file" dest="file" />
</recipe>
```
leads to:
```
Traceback (most recent call last):
File "0template.py", line 124, in <module>
  process_archives(elem)
File "0template.py", line 116, in process_archives
  process_archives(elem)
File "0template.py", line 97, in process_archives
  tmpdir = unpack.unpack_to_tmp(href, local_copy, elem.getAttribute('type'))
File "unpack.py", line 15, in unpack_to_tmp
  assert mime_type, "Can't guess MIME type from {url}".format(url = url)
AssertionError: Can't guess MIME type from http://some/file
```

It seems to be trying to guess the MIME type for a ```<file>``` as if it were an ```<archive>```.

**Comment by talex5** [comment]
Does it work if you add `extract=''` to it (as a work-around for this bug)?
